sudo: true
language: node_js
node_js:
  - '9'
os: osx
install:
  - npm install -g node-gyp
  - npm install -g electron-packager
  - npm install
  - electron-packager . locator --overwrite --platform=darwin --arch=x64 --icon=asset/logo.icns --prune=true --out=release-builds
before_deploy:
  - cd release-builds/locator-darwin-x64
  - zip -r minerstat-locator-mac.zip .
  - git config --local user.name "coinscrow"
  - git config --local user.email "info@minerstat.com"
  - if [ -z "$TRAVIS_TAG" ] ; then TRAVIS_TAG=latest; fi
deploy:
  provider: releases
  api_key:
    secure: qcrPoxQBskajgE6DE54qlD0IjahS02ksigvSwY8YYjaYF8+iheSz1Y6la/FWok4B7NKV/9ilkD4X52KUINPQbesx6BGDlA2Czm/qEVHkqm9QglrVi+Va8Kl3AKfJFy+ganWT1uyP5xUo6G+tGCRhUI0+wyga9E5Jmm9o4PMNfNELICGv4+VAg18ohUe9ujYrmtXMkqzAhasf2zEuJ4dxHkgFP6NF8k31WfqgtP2sot1MCX7E997Ymf7a1Se0ZdltypXPVhPJvd3LWqRkLcv2TVLnrARJv75lKxwDXWtU1ElK9KD2t6uxGRx3IquFmTOLiP7WVm5CA1g5jFyFIJmAAkTChjtJX/yvmsmkvYPqssrleh/qmCvIW/o35pfTjWQ7cEoVCW27ltObT0rrHCw5r8fpMPy1LHuaoJsuKuqQHtzRskvReI1sVCPM46uefoIQd6ap5OzvR6QxyktSNxaL7PUnSxiLpa5OpjXd57Pm6Ir2DC6WrZf1jdIGUSb1v+NYsQZX2EA0dgte0LixHiUL7I1jUZU3L4KqcJZTsKc9TYxrpOE/z+6juqxCIaBf6rPi4cVY+Pnb/T5niZNZ4L3H1LfiMz/7PrCZoG8USFhxukehpRaU4po6rrbjPvJS6mTzUUQlUg8iAYxPKM3c/RHxhl4zl9LoqOhORteqr8raIbg= 
    file: "$TRAVIS_BUILD_DIR/release-builds/locator-darwin-x64/minerstat-locator-mac.zip"
  skip_cleanup: true
  overwrite: true
  prerelease: true
  draft: false
  on:
    tags: false
    branch: master
